# Generated by Django 5.0.2 on 2024-04-18 11:25

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('artical', tinymce.models.HTMLField()),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('heading2', models.CharField(max_length=999)),
                ('enable', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True, unique=True)),
                ('text', models.TextField(blank=True, max_length=9999, null=True)),
                ('IMG', models.ImageField(blank=True, null=True, upload_to='carousel/img1')),
                ('link_lable1', models.CharField(blank=True, max_length=9999, null=True)),
                ('link1', models.CharField(blank=True, max_length=9999, null=True)),
                ('link_lable2', models.CharField(blank=True, max_length=9999, null=True)),
                ('link2', models.CharField(blank=True, max_length=9999, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('Enable', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('text', models.TextField(max_length=9999)),
                ('name', models.CharField(max_length=9999)),
                ('designation', models.CharField(max_length=9999)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=999)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description_1', models.TextField(max_length=12000)),
                ('Enable', models.BooleanField(default=False)),
                ('index', models.BooleanField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=12000)),
                ('Enable', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
                ('right', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Enable', models.BooleanField(default=True)),
                ('index', models.BooleanField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=999)),
                ('description', models.TextField(max_length=12000)),
                ('overview', models.TextField(max_length=12000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('catalogue', models.FileField(upload_to='catalogue/')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('table_head', models.CharField(blank=True, default='Technical Specification', max_length=999, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.catagory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('Prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.products')),
            ],
        ),
    ]
