# Generated by Django 5.0.2 on 2024-04-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='left',
        ),
        migrations.RemoveField(
            model_name='service',
            name='right',
        ),
    ]
