# Generated by Django 5.0.2 on 2024-04-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=12000)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
