# Generated by Django 5.0.2 on 2024-04-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_top_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_content',
            name='icon',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
