# Generated by Django 5.0.2 on 2024-04-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_top_content_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='top_content',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
